## Numpy

In [2]:
import numpy as np

Основные типы данных в numpy — это [numpy.array](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html) и [numpy.matrix](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.matrix.html) 

### numpy.array 

In [4]:
a = [1, 2, 3]
numpy_a = np.array(a)
print(type(numpy_a))

<class 'numpy.ndarray'>


In [10]:
#Важно! 
#List можно заполнять элементами различного типа, а вот numpy.array нет
a = [1, 'a', [1, 2]]
numpy_a = np.array(a)

ValueError: setting an array element with a sequence

In [13]:
#Можно создавать пустой массив
empty_array = np.empty(5)
print(empty_array)

# ... а можно заполненный нулями
zeros_array = np.zeros(5)
print(zeros_array)

# ... а можно - еденичками
ones_array = np.ones(5)
print(ones_array)

[  1.90801354e-316   6.91063618e-310   6.91063915e-310   5.39089651e-317
   6.91059236e-310]
[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]


In [15]:
#Можно создавать двумерные массивы
zeros_array2 = np.zeros((5, 5))
сprint(zeros_array2)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [18]:
# ... а можно трехмерные и, вообще, скольки хочешь мерные 
zeros_array3 = np.zeros((2, 2, 2))
print(zeros_array3)

[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]


Обращаться к элементу numpy.array нужно также, как и к элементу list - через оператор квадратные скобочки. Заметим также, что numpy.array изменяемый тип данных.

### Задача 1
Создайте матрицу у которой на диоганали стоят единицы, а все остальные элементы нули (единичная матрица) размера 10*10

In [13]:
a = np.zeros((10, 10))
for index in range(len(a)):
    a[index][index] = 1
a

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [28]:
#Задачу 1 можно решить с помощью одной команды из numpy
numpy_eye = np.eye(10)
print(numpy_eye)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [22]:
#Эквивалент range
numpy_range = np.arange(10,35)
print(numpy_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


In [27]:
#Размерность
print(numpy_range.shape)

print()
numpy_reshape = numpy_range.reshape((5, 5))
print(numpy_reshape)
print(numpy_reshape.shape)

(25,)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
(5, 5)


In [38]:
#На втором семинаре мы решали задачу 3 про удаление нулей из списка
#С помощью модуля numpy можно найти индексы не нулевых элементов 
numpy_a = np.array([1,2,0,0,4,0])
nz_indices = np.nonzero(numpy_a)
print('Non zero indices', nz_indices)
#Теперь мы можем вернуть не нулевые элементы следующим образом
print(numpy_a[nz_indices])
#Таким образом ту задачу можно было бы решить в одну строчку
numpy_nonzero_a = numpy_a[np.nonzero(numpy_a)]

Non zero indices (array([0, 1, 4]),)
[1 2 4]


In [42]:
#Ещё несколько возможностей
a = np.random.random((10,10))
print('Create ramdom array:\n', a)
a_min, a_max = a.min(), a.max()
print('min: %f, max: %f'%(a_min, a_max))
a_mean = a.mean()
print('mean: %f'%a_mean)

Create ramdom array:
 [[ 0.87513703  0.52260881  0.7196248   0.96103319  0.4006673   0.11093142
   0.70531983  0.99321753  0.01347965  0.55493718]
 [ 0.98448192  0.38580245  0.49511084  0.65237444  0.05558738  0.50684954
   0.85049787  0.51269571  0.45976561  0.2627926 ]
 [ 0.85246388  0.25319759  0.05763801  0.67994401  0.36639767  0.1196675
   0.20189263  0.32814897  0.31149614  0.19448329]
 [ 0.61570368  0.62488868  0.24558466  0.94808382  0.29333595  0.95671898
   0.80895455  0.23025789  0.16740505  0.51970777]
 [ 0.35237373  0.43702743  0.46870189  0.80363372  0.88963693  0.48069648
   0.18514255  0.75868915  0.6030863   0.66248844]
 [ 0.48636378  0.23297415  0.98094837  0.50388855  0.04248549  0.19249448
   0.98345356  0.97960102  0.47224612  0.73614328]
 [ 0.25564005  0.06384703  0.50324637  0.57031748  0.55197003  0.27050325
   0.47267018  0.31245399  0.18112827  0.84136876]
 [ 0.86635415  0.43604209  0.96671748  0.45343373  0.3006502   0.57833524
   0.3331649   0.00709151  0.9

In [9]:
#Бесконечность и неопределённость
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.inf - np.inf)

nan
False
False
nan
nan


In [48]:
#Немного о странностях вещественных чисел
print(0.3 == 3 * 0.1)
print(0.3, 3*0.1)

False
0.3 0.30000000000000004


### Задача 2
Создайте вот такую матрицу 

[[ 1.  0.  0.  0.  0.]

 [ 1.  1.  0.  0.  0.]
 
 [ 0.  2.  1.  0.  0.]
 
 [ 0.  0.  3.  1.  0.]
 
 [ 0.  0.  0.  4.  1.]]

In [41]:
numpy_eye = np.eye(5)
for index in range(1, len(numpy_eye)):
    numpy_eye[index][index-1] = index
numpy_eye

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  1.]])

In [42]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [47]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
np.eye(5)+np.diag([1, 2, 3, 4], k=-1)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  1.]])

In [51]:
#А теперь как решить это в одну строчку
a = np.eye(5)+np.diag(1+np.arange(4),k=-1)
print(a)

[[ 1.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  2.  1.  0.  0.]
 [ 0.  0.  3.  1.  0.]
 [ 0.  0.  0.  4.  1.]]


### Задача 3 
Напишите функцию, которая на вход принимает numpy.array и возвращает нормализованый массив

Сгенерируйте случайную квадратную матрицу размера 5 и проверьте свою реализацию 

In [53]:
def norm(input_array):
    a_min = input_array.min()
    a_max = input_array.max()
    return (input_array-a_min)/(a_max-a_min)

norm(np.random.random((5, 5)))

array([[ 0.28367676,  0.30034424,  0.74883951,  0.7093101 ,  0.56891821],
       [ 0.70540835,  0.73684095,  0.02647481,  0.05700687,  0.12866134],
       [ 0.66566849,  0.92423232,  0.        ,  0.60623921,  0.94885938],
       [ 0.22812336,  0.66513878,  0.07054385,  0.43522094,  0.3749321 ],
       [ 0.69731223,  1.        ,  0.20374526,  0.24998012,  0.88860289]])

### Задача 4 

Напишите функцию, которая принимает на вход два двумерных numpy.array и возвращает результат их перемножения. [Умножение матриц](https://ru.wikipedia.org/wiki/%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86) 

In [53]:
#Задачу 4 можно легко решить с помощью np.dot()
print(np.dot(np.ones((5,3)), np.ones((3,2))))

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### Задача 5
Напишите функцию, реализующую транспонирование матрицы

In [55]:
#Задачу 5 можно легко решить с помощью a.T
a = np.eye(5)+np.diag(1+np.arange(4),k=-1)
print(a)
print('Transpose:')
print(a.T)

[[ 1.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  2.  1.  0.  0.]
 [ 0.  0.  3.  1.  0.]
 [ 0.  0.  0.  4.  1.]]
Transpose:
[[ 1.  1.  0.  0.  0.]
 [ 0.  1.  2.  0.  0.]
 [ 0.  0.  1.  3.  0.]
 [ 0.  0.  0.  1.  4.]
 [ 0.  0.  0.  0.  1.]]


На последок немного о том как добавлять элементы в numpy.array

[numpy.append](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.append.html)

[numpy.concatenate](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html)

[numpy.hstack](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html)

[numpy.vstack](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html)